### ISSUE TITLE
Inference result of official API code is not consistent with model.inference()

### ISSUE THREAD

**Issue by tydusky** [shangtse/robust-physical-attack#6]
First, we generate an adversarial image that recognized as a person from a horse image.
Then, we use ` model.inference(image) ` function to inference and visualize the image.
We get 
![image](https://user-images.githubusercontent.com/18514264/47502743-22318000-d89b-11e8-8da2-7e01962a381a.png)
But when I use the official API
 [run_inference_for_single_image(image, graph)](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) 
we get 
![image](https://user-images.githubusercontent.com/18514264/47502914-7ccadc00-d89b-11e8-8f7e-9f5fc62a55a0.png)
which can still be recognized as horse.
I'm really confused about it.

**Comment by shangtse** [comment]
Are you sure you used the same model? In your link, the default model used is "ssd_mobilenet_v1_coco_2017_11_17, " while in our code we used "faster_rcnn_inception_v2_coco_2017_11_08." Just wanted to make sure that you have changed the model name.
If that's not the problem, could you paste your entire code (or at least give me more details in order to debug)?

**Comment by tydusky** [comment]
> Are you sure you used the same model? In your link, the default model used is "ssd_mobilenet_v1_coco_2017_11_17, " while in our code we used "faster_rcnn_inception_v2_coco_2017_11_08." Just wanted to make sure that you have changed the model name.
> If that's not the problem, could you paste your entire code (or at least give me more details in order to debug)?

I have changed the model name.
I send the entire code to your email (b95100@gmail.com).

**Comment by shangtse** [comment]
It seems that you changed the code quite a bit (e.g., instead of overlay the patch to the background image, you are trying to do the imperceptible-noise-style perturbation). 
Have you tried the original code and see whether run_inference_for_single_image(image, graph) still gives you the desired result? 
If the original code gives the correct result and your version give incorrect result, you can gradually change the code to debug.

I haven't fully understand your code, but I noticed something strange.
E.g., 
patched_input_ = tf.clip_by_value(self.image_input_/255.0 + img_mask * self.clipped_patch_, clip_value_min=-1.0, clip_value_max=1.0)
Not sure what do you want to do, but self.clipped_patch_ is in [-1, 1] and self.image_input_/255.0 is in [0, 1].

Also you changed 
self.patched_input_ = tf.fake_quant_with_min_max_vars((patched_input_ + 1)*127.5, min=0, max=255)
to
self.patched_input_ = tf.fake_quant_with_min_max_vars(patched_input_ * 255, min=0, max=255)
which may cause some problem.
